volumes:
  elasticsearch-data:
    external: true

services:
  elasticsearch:
    image: 'elasticsearch:${ELASTICSEARCH_IMAGE_TAG}'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data/
    env_file:
      - ./elasticsearch/.env
