volumes:
  bitnami-mysql:
    external: true

services:
  mysql:
    image: 'bitnami/mysql:${MYSQL_IMAGE_TAG}'
    env_file:
      - ./mysql/.env
    volumes:
      - bitnami-mysql:/bitnami/mysql/data
      - ./mysql/sql:/sql
