volumes:
  mysql-data:
    external: true

services:
  mysql:
    image: 'mysql:${MYSQL_IMAGE_TAG}'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=1
      - --secure-file-priv=/sql
    env_file:
      - ./mysql/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/sql:/sql
