volumes:
  minio-data:
    external: true
#  minio-client-data:
#    external: true

services:

  minio:
    image: minio/minio:${MINIO_IMAGE_TAG}
    command:
      - minio
      - server
      - /data
      - --console-address
      - :${MINIO_CONSOLE_PUBLISH_PORT:-9001}
    restart: "no"
    env_file:
      - ./minio/.env
    volumes:
      - minio-data:/data

#  minio-client:
#    image: minio/mc:${MINIO_CLIENT_IMAGE_TAG}
#    command: [ "--version" ]
#    restart: "no"
#    depends_on:
#      - minio
#    networks:
#      - docker-net
#    volumes:
#      - minio-client-data:/root/.mc
#
#  minio-nginx:
#    image: nginx:${MINIO_NGINX_IMAGE_TAG:-alpine}
#    restart: "no"
#    depends_on:
#      - minio
#    networks:
#      - docker-net
#    volumes:
#      - ./minio/nginx/conf.d:/etc/nginx/conf.d
#      - ./minio/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./minio/nginx/certs:/etc/nginx/certs
